### PR TITLE
doc: Add docu for 'ssi-agent-lib'

### PR DESCRIPTION
**Pull request by bjoern-arnold**
## Description
Added overview documentation of [ssi-agent-lib](https://github.com/eclipse-tractusx/SSI-agent-lib).

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [-] DEPENDENCIES: not applicable, only documentation.
- [-] Copyright and license header: not applicable, only documentation.

### CODE REVIEW

**Comment by bjoern-arnold** [comment]
Hi @wolf4ood, can you please review my PR? Thx!

**Comment by jimmarino** [comment]
I'm not sure this repository is the correct place for this document - I think this should go into the SSI Libn repo. Moving forward, this repo will be for the standardization work around SSI.

**Review by paullatzelsperger — CHANGES_REQUESTED** [review]
Generally speaking, documentation about "implementation details", such as the SSI-Agent-Lib should go in that particular project's repository, here: the SSI-Agent-Lib. 
After all, it is up to wallet implementors whether or not they choose to use the SSI-Agent-Lib.
Please close this PR, and re-open it in the SSI-Agent-Lib repository.

**Comment by florianrusch-zf** [comment]
I am closing this as it seems to be already included: https://github.com/eclipse-tractusx/SSI-agent-lib/blob/main/docs/Architecture.md

**Pull request closed without merging**
