### PR TITLE
docs: add compliance specification for tests

### PR DESCRIPTION
**Pull request by paullatzelsperger**
## WHAT

adds a documentation/specification document regarding compliance tests for Issuer and Verifier implementations, referencing the TCK project.

## WHY

having multiple possible wallet and issuer impls. requires a common understanding of functional compliance.

### CODE REVIEW

**Comment by paullatzelsperger** [comment]
\cc @jimmarino

**Review by wolf4ood — APPROVED** [review]
LGTM

**Comment by jimmarino** [comment]
Nice write-up. The approach I think we should take is a document-first approach similar to what the W3C does. We can follow that up later with automated tests. 

We should have a document that numbers all of the tests, includes sample messages and identifies the expected outcome. People can choose to go off the document or run the (future) automated tests.

**Review by jimmarino — APPROVED** [review]

**Comment by paullatzelsperger** [comment]
> Nice write-up. The approach I think we should take is a document-first approach similar to what the W3C does. We can follow that up later with automated tests.

That makes sense. So how about this then: i'll move the test specification to another file, which is referenced from "this" file, so we can improve on it independently.

**Pull request merged**
